name: build-and-test

on: push

jobs:

  BuildAndTest:

    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Installing valgring and cpplint
      run: |
          sudo apt install valgrind
          sudo pip install cpplint
          cpplint --help
          
    - name: Test them all
      run: make all -C Lab3/
